name: Multiverse-Legacy-Api
version: ${version}
main: com.onarandombox.MultiverseCore.MultiverseCore
api-version: '1.13'
authors: [ benwoo1110 ]
description: Adds legacy support for Multiverse-Core v4 api
loadbefore: [ 'Multiverse-Core' ]
